### PR TITLE
MNT: bump AD version to 3.3.2

### PR DESCRIPTION
**Pull request by tacaswell**

### CODE REVIEW

**Review by mrakitin — APPROVED** [review]
Looks like a good improvement!

**Comment by tacaswell** [comment]
Probably should have waited for @klauer to have a look at this...

**Comment by mrakitin** [comment]
Sorry I hurried up :). Do you prefer a revert?

**Comment by tacaswell** [comment]
No, and the cannonical upstream in @klauer 's anyway...

**Comment by mrakitin** [comment]
Got it! Will consider @klauer's input in the future regarding this project.

**Pull request merged**
